---
- hosts: all
  gather_facts: no
  tasks:
    - name: Stop SAP application
      shell: |
        cd /home/esipct24/bin
        sh pctcog.sh
        cd /home/esipct24/data
       expect << 'EOS'
       spawn sftp esiadmin@us.ibm.com@9.209.252.223
       expect "Password:"
       send "PASSWORD\n"
       EOS
