---
- hosts: all  
  gather_facts: no
  tasks:
    - name: copy from one system to another
      shell: scp /home/esipct24/data/pct.tar.bz2 esiadmin@us.ibm.com@dgawdcdeng301.sl.bluecloud.ibm.com:/ISData/Data/DEV/DMMPROC/ESI_PCT/ftp/esipct/
      
